export const getData =
    [
        {
          "CustomerID":1,
          "CustomerCode":"3001",
          "CustomerName":"株式会社ノア",
          "Address":"札幌市中央区",
          "CustomerClassID":2,
          "PrefecturalID":1,
        },
        {
          "CustomerID":2,
          "CustomerCode":"3002",
          "CustomerName":"株式会社JTB北海道",
          "Address":"札幌市中央区",
          "CustomerClassID":2,
          "PrefecturalID":1,
        },
        {
          "CustomerID":3,
          "CustomerCode":"3003",
          "CustomerName":"国分株式会社",
          "Address":"札幌市中央区",
          "CustomerClassID":2,
          "PrefecturalID":4,
        },
    ];